#!/bin/dash

##
# This script is invoked by render script
#
# param $1 = file name
# param $2 = test name
#
# Exatract each particular test to its own result file.
# Store only execution times for plotting.
# Finally create a simple plot combining all three results.
##

fname="$1"
grep -v Scenario "$fname" | \
grep " $2Vector" | \
awk '{print $3}' > datA

grep -v Scenario "$fname" | \
grep " $2BArray" | \
awk '{print $3}' > datB

grep -v Scenario "$fname" | \
grep " $2TreeSet" | \
awk '{print $3}' > datC

gnuplot <<EOF

set autoscale
set nokey
set yrange [1:]
#unset border
set border 15 linecolor rgb 'grey70'
unset ytics
unset xtics
set log y
set title "$2"

set terminal png size 320,200
set output 'BArray-$2.png'

plot "datA" with linespoints, "datB" with linespoints, "datC" with linespoints

EOF

